---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: 8.x

projects:

  drupal:
    type: core
    version: 8.0.x

  devel: 1.x-dev


  #cd $DIRECTORY/'build/modules'
  #$DRUSHPATH/drush dl ds
  #$DRUSHPATH/drush dl devel
  #$DRUSHPATH/drush dl honeypot

  #git clone --branch 8.x-3.x http://git.drupal.org/sandbox/grayside/2120935.git features
  #git clone --branch d8panels http://git.drupal.org/sandbox/dsnopek/2290237.git d8panels
